packaging_format = 2

id = "redmine"
name = "Redmine"
description.en = "Flexible project management web application"
description.fr = "Gestionnaire de projet flexible sous forme d'application web"

version = "5.0.4~ynh1"

maintainers = [""]

[upstream]
license = "GPL-2.0"
website = "https://www.redmine.org"
code = "https://github.com/redmine/redmine"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/redmine/redmine/archive/refs/tags/5.0.4.tar.gz"
        sha256 = "131ef749ac40af475374659d69dfa53e02a520c6354857fc24dfce5b9443cad3"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, libpq-dev"

    [resources.database]
    type = "postgresql"
