#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_ruby__2
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Ruby..." --weight=1

ynh_exec_warn_less ynh_install_ruby --ruby_version=$ruby_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/files" "$install_dir/log" "$install_dir/tmp" "$install_dir/public/plugin_assets"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration file..." --weight=1

ynh_add_config --template="database.example.yml" --destination="$install_dir/config/database.yml"
chmod 400 "$install_dir/config/database.yml"
chown "$app:$app" "$install_dir/config/database.yml"

ynh_add_config --template="configuration.yml.example" --destination="$install_dir/config/configuration.yml"
chmod 400 "$install_dir/config/configuration.yml"
chown "$app:$app" "$install_dir/config/configuration.yml"

ynh_add_config --template="../conf/db-ldap.sql" --destination="$install_dir/config/db-ldap.sql"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..." --weight=1

_redmine_ruby_install

pushd "$install_dir"
	ynh_exec_warn_less bundle exec rake generate_secret_token RAILS_ENV=production
	ynh_exec_warn_less bundle exec rake db:migrate RAILS_ENV=production

	#Setting up LDAP authentification
	ynh_psql_connect_as $db_user $db_pwd $db_name < $install_dir/config/db-ldap.sql
	ynh_secure_remove --file="$install_dir/config/db-ldap.sql"
	
	#ynh_exec_warn_less bundle exec rake redmine:load_default_data RAILS_ENV=production
popd

# Setting up LDAP authentification
ynh_add_config --template="db-ldap.sql" --destination="$install_dir/config/db-ldap.sql"
ynh_psql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < "$install_dir/config/db-ldap.sql"
ynh_secure_remove --file="$install_dir/config/db-ldap.sql"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log" --line_match="WEBrick::HTTPServer#start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
