#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading Ruby..."

ynh_ruby_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config/database.yml config/configuration.yml config/initializers/secret_token.rb"

mkdir -p "$install_dir/files" "$install_dir/log" "$install_dir/tmp" "$install_dir/public/plugin_assets"

chmod 750 "$install_dir/files" "$install_dir/log" "$install_dir/tmp" "$install_dir/public/plugin_assets"
#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

_redmine_ruby_install
pushd "$install_dir"
    ynh_hide_warnings bundle exec rake db:migrate RAILS_ENV=production
popd

# Setting up LDAP authentification
ynh_config_add --template="db-ldap.sql" --destination="$install_dir/config/db-ldap.sql"
ynh_psql_db_shell < "$install_dir/config/db-ldap.sql"
ynh_safe_rm "$install_dir/config/db-ldap.sql"

chmod 750 "$install_dir/public"
chmod -R o-rwx "$install_dir/public"
chown -R "$app:www-data" "$install_dir/public"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="WEBrick::HTTPServer#start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
